DB_HOST: "localhost"
DB_PORT: 3306
DB_USER: "root"
DB_PASS: ""
DB_NAME: "bills"
CRYPT_KEY: "vz7oWXaUm691nvAwXJuvs9U6UM04ZZs0"
TOKEN_KEY: "XvkAKPFg6vHQ930PRt13REOZjJuAu0b9fbLaqXC8"
PUSHER_APP_ID: "312972"
PUSHER_APP_KEY: "5669f8456559d3ad11ad"
PUSHER_APP_SECRET: "e0a9f9514d0879af7746"
PUSHER_CLUSTER: "ap1"
PUSHER_CHANNEL: "ADS_CLIENTS"
PUSHER_EVENT: "INQUIRY"
